image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  except:
    refs:
      - master
  script:
    - yarn
    - yarn lint
    - yarn build
    - yarn test

deploy:
  stage: deploy
  # only:
  #   refs:
  #     - master
  script:
    - echo "//gitlab.example.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" > .npmrc
    - yarn
    - yarn build
    - yarn test
    - yarn publish
