image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  except:
    refs:
      - master
  script:
    - yarn
    - yarn lint
    - yarn build
    - yarn test

deploy:
  stage: deploy
  # only:
  #   refs:
  #     - master
  script:
    - |
      {
        echo "@${CI_PROJECT_ROOT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/"
        echo "${CI_API_V4_URL#https?}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=\${CI_JOB_TOKEN}"
      } | tee --append .npmrc
    - yarn
    - yarn build
    - yarn test
    - yarn publish
