default:
  image: node:18
  before_script:
    - corepack enable

stages:
  - test
  - tag
  - publish

test:
  stage: test
  except:
    - tags
  script:
    - yarn
    - yarn lint
    - yarn build
    - yarn coverage # includes yarn test

tag:
  stage: tag
  only:
    - master
  script:
    - npx semantic-release@20 --repository-url `git remote get-url origin`

publish-to-npm:
  stage: publish
  only:
    - tags
  script:
    - |
    - ./scripts/createAndPublishSBOM.sh
      echo "
      npmPublishRegistry: \"https://registry.npmjs.org/\"
      npmAlwaysAuth: true
      npmAuthToken: \"${NPM_TOKEN}\"" >> .yarnrc.yml
    - 'sed -ie "s/\"version\":[ ]*\"[^\"]*\"/\"version\": \"`git describe --tags | tr -d v`\"/g" package.json'
    - 'sed -i "/^[ ]*\"prepare\": \".*\",$/d" package.json'
    - yarn
    - yarn npm publish --access public

publish-to-gitlab:
  stage: publish
  only:
    - tags
  script:
    - |
      echo "
      npmScopes:
        ${CI_PROJECT_ROOT_NAMESPACE}:
          npmRegistryServer: \"https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/\"
          npmPublishRegistry: \"https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/\"
          npmAlwaysAuth: true
          npmAuthToken: \"${CI_JOB_TOKEN}\"" >> .yarnrc.yml
    - 'sed -ie "s/\"version\":[ ]*\"[^\"]*\"/\"version\": \"`git describe --tags | tr -d v`\"/g" package.json'
    - 'sed -i "/^[ ]*\"prepare\": \".*\",$/d" package.json'
    - yarn
    - yarn npm publish
