export enum FillColor {
    BACKGROUND = -1,
    BLACK = 0,
    BLUE = 1,
    GREEN = 2,
    CYAN = 3,
    RED = 4,
    MAGENTA = 5,
    YELLOW = 6,
    WHITE = 7,
    GRAY = 8,
    LIGHT_BLUE = 9,
    LIGHT_GREEN = 10,
    LIGHT_CYAN = 11,
    LIGHT_RED = 12,
    LIGHT_MAGENTA = 13,
    BROWN = 14,
    LIGHT_WHITE = 15,
    BLINK = 16,

    /** Fuellfarben - Benutzerdefiniert */
    USER_MIN = 17,
    USER_MAX = 69,
    USER_CLEAR = 70,
}