export const TAGS = {
  ProcessingSide: {
    name: 'PROCESS_SIDE', // Bearbeitungsseite (oben/unten)
    BOTTOM: 'BOTTOM',
    TOP: 'TOP',
  },
  ProcessingType: {
    name: 'PROCESS_TYPE', // Bearbeitungstyp (schneiden, kennzeichnen,..)
    CUT: 'CUT',   // schneiden
    MARK: 'MARK', // kennzeichnen
    NONE: 'NONE', // ignorieren
    FORM: 'FORM', // umformen
    FOIL_REMOVAL: 'FOIL_REMOVAL',  // Folienabziehhilfe
    CODE: 'CODE', // data matrix code
    LABEL_DATAMATRIX: 'LABEL_DATAMATRIX', // data matrix code
    LABEL_TEXT: 'LABEL_TEXT', // label text
  },
  ProcessTemplate: {
    name: 'PROCESS_TEMPLATE', // Bearbeitungsvorlage (Teilebeschriftung II)
  },
  LaserInternal: {
    name: 'LaserInternal', // for internal laser use
  },
  AutoGenerated: {
    name: 'AutoGenerated', // fuer automatisch erzeugte Elemente
  },
};

export class TagAttribute {
  constructor(public name: string, public value: string, public type: number) {
  }

  static fromText(text: string[]) {
    return new TagAttribute(
      text.length > 1 ? text[1] : '',
      text.length > 0 ? text[0] : '',
      text.length > 2 ? +text[2] : 0);
  }

  toText() {
    return [this.name, this.value, `${this.type}`];
  }
}
